### ISSUE TITLE
Recorrido máximo Z

### ISSUE THREAD

**Issue by Marcramoscosta** [BCN3D/BCN3DSigmax-Firmware#3]
Cuando realizamos una impresión de 209mm de altura y al finalizar apagamos la maquina, al encenderla baja el eje y golpea en el relee y en algunos casos se clava el eje

**Comment by AlejandroGarcia92** [comment]
Estoy en ello.

**Comment by AlejandroGarcia92** [comment]
Hecho en la version 2.0.5 de fw
