### ISSUE TITLE
Incorrect return value of Listfiles::search_line_data_commentary()

### ISSUE THREAD

**Issue by dvb-adenin** [BCN3D/BCN3DSigmax-Firmware#4]
https://github.com/BCN3D/BCN3DSigmax-Firmware/blob/dcbb42bc6440805ec9c5b234a2d460505467e665/Marlin/SD_ListFiles.cpp#L41

search_line_data_commentary() never returns -1
This occurs several times in the code.

This is the erroneous code:
https://github.com/BCN3D/BCN3DSigma-Firmware/blob/47cf3ba8d4484a16f9770453597f402596573318/Marlin/SD_ListFiles.cpp#L175

**Comment by AlejandroGarcia92** [comment]
I will take a look. The fix should be something like that:
```
int Listfiles::search_line_data_commentary(){
	char serial_char='\0';
	int posi = 0;
	int exit = 0;
	while(commandline[0]!=';' && !card.isEndFile()){
		serial_char='\0';
		posi = 0;
		while(serial_char != '\n' && posi < 49 && !card.isEndFile()){
			
			int16_t n=card.get();
			serial_char = (char)n;
			commandline[posi]=serial_char;
			
			posi++;
		}
		exit++;
		if(exit>20 || card.isEndFile()){
			return -1;// <--- FIX
		}
	}
	return 0;
}
```
