### ISSUE TITLE
BCN3D Sigmax R19 Freezing At Main Menu and Loading Screen

### ISSUE THREAD

**Issue by alexb26** [BCN3D/BCN3DSigmax-Firmware#5]
Hello,

I've been having a issue, starting today, with the Sigmax R19 LCD Screen being unresponsive and freezing during calibration and start up. I have tried power cycling and that have no effect on fixing the issue. The printer is on Firmware Version 2.0.7. It also seems to have an issue with aborting prints using the USB print. If there is anything I can check or try to fix the issue, I would appreciate the help.

Thank you.

**Comment by AlejandroGarcia92** [comment]
Hi @alexb26, I need two things: 1 screenshot of Utilities screen and the full firmware version name (e.g. 02-2.0.7 or 01-2.0.7). My apologise for the inconvenience.

**Comment by alexb26** [comment]
So funnily enough, the machine is working fine now. The version number is 02-2.0.7 but I can't get a picture of the freezing because it hasn't happened yet. Thank you for your hard work!

**Comment by AlejandroGarcia92** [comment]
Ok, as I know, this issue can be related with the quality of the contact between screen sd socket and sd card(lcd sd card).

**Comment by alexb26** [comment]
Okay, so this issue has happened again. This time I got pictures. Is there any known fix for this or is it just something that can't be addressed?
![20190703_091245 1](https://user-images.githubusercontent.com/52180431/60608139-9e0d9180-9d73-11e9-9c41-c3f6b85884e9.jpg)
![20190703_091454 1](https://user-images.githubusercontent.com/52180431/60608194-baa9c980-9d73-11e9-9271-40bde4fbfd35.jpg)

**Comment by alexb26** [comment]
New Addition to this issue: LCD now registers one touch as multiple touches.

**Comment by AlejandroGarcia92** [comment]
The only process that you can try is to format the sd card and hope. The other issues can be addressed to a LCD malfunction so you will need to contact support.
