### ISSUE TITLE
Confirmation of firmware file size?

### ISSUE THREAD

**Issue by Krammer002** [BCN3D/BCN3DSigmax-Firmware#6]
Just a quick sanity check... Should the compiled file size resemble this:

Sketch uses 238104 bytes (93%) of program storage space. Maximum is 253952 bytes.
Global variables use 7316 bytes (89%) of dynamic memory, leaving 876 bytes for local variables. Maximum is 8192 bytes.
Low memory available, stability problems may occur.

Also which version should i use: Marlin.ino.mega.hex or Marlin.ino.with_bootloader.mega.hex?
Thanks

**Comment by AlejandroGarcia92** [comment]
I use Marlin.ino.hex

**Comment by Krammer002** [comment]
Thank you

What  Arduino compiler do you use?

Thanks

**Comment by AlejandroGarcia92** [comment]
Arduino 1.8.9 for Atmega2560 MCU. I'm thinking that Marlin.ino.mega.hex could be the good one. Do not install the bootloader version.

**Comment by Krammer002** [comment]
Thanks, i’ll Give it try...

**Comment by Krammer002** [comment]
Just one more thing... My compiled file size is  654 KB (669,738 bytes). The pre-compiled v02-2.0.8.hex version on Github shows the size to be smaller 639KB. is this normal?

**Comment by AlejandroGarcia92** [comment]
Does your compilation for Sigma or Sigmax?

**Comment by AlejandroGarcia92** [comment]
I don't know what you mean.

**Comment by Krammer002** [comment]
Different file size  My modified file 654KB, your v02-2.0.8 compiled file 639KB

**Comment by AlejandroGarcia92** [comment]
![Captura](https://user-images.githubusercontent.com/17469944/64118488-10ace480-cd98-11e9-9da5-0461379799a3.PNG)

I see 654KB on my hex. (https://github.com/BCN3D/BCN3DSigmax-Firmware/releases/tag/02-2.0.8)

**Comment by Krammer002** [comment]
OK my mistake... I was looking at the compiled info:  14877 lines (14876 sloc)  639 KB
I've compiled and uploaded to my Sigmax and all appears to be working...  Thank you
